#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 快捷指令(推荐): 设置地理位置https://www.icloud.com/shortcuts/6560cced670441939e4ca08fc2a8f8ac 清理恢复位置 https://www.icloud.com/shortcuts/e8810b79f6a6405dacda4046b7534b57 
#!author=ciaooo66 Rewrite
#!homepage=https://github.com/ciaooo66/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
