#!name=Apple WLOC 定位修改
#!desc=Quantumult X 圈 X | 支持网页/快捷指令写入校验，未命中重写时不误报成功
#!author=ciaooo66
#!homepage=https://github.com/ciaooo66/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
