#!name=虚拟定位模块
#!desc=Shadowrocket 小火箭 | 支持网页/快捷指令写入校验，未命中模块时不误报成功 快捷指令：修改定位：https://www.icloud.com/shortcuts/f5aa9c61bb4e4810a2c2f897680fcb0f 恢复定位：https://www.icloud.com/shortcuts/798f69f9e1344dc9b0f44f36a7e29968
#!author=ciaooo66
#!homepage=https://github.com/ciaooo66/wloc
#!icon=https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/wloc.jpg
#!category=Tools

[Rule]
DOMAIN,gs-loc.apple.com,DIRECT
DOMAIN,gs-loc-cn.apple.com,DIRECT

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
