#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭) | 快捷指令(推荐): 设置地理位置 https://www.icloud.com/shortcuts/25c4b48dae044648a6bc13248d5cc86c 清理恢复位置 https://www.icloud.com/shortcuts/e8810b79f6a6405dacda4046b7534b57 
#!homepage=https://github.com/ciaooo66/wloc
#!icon=https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/wloc.jpg
#!category=Tools
[Rule]
DOMAIN,gs-loc.apple.com,DIRECT
DOMAIN,gs-loc-cn.apple.com,DIRECT
[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/ciaooo66/wloc/refs/heads/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
